SELECT 
-- from ORDER
O.ORDERID
,O.ORDERDATE
,O.SHIPDATE
,O.SHIPMODE
,O.CUSTOMERID AS CUST
,O.PRODUCTID AS PRODID
,O.ORDERCOSTPRICE
,O.ORDERSELLINGPRICE
--from customer
,C.CUSTOMERID
,C.CUSTOMERNAME
,C.SEGMENT
,C.COUNTRY
,C.STATE  
--from PRODUCT
,P.CATEGORY
,P.PRODUCTID
,P.PRODUCTNAME
,P.SUBCATEGORY
,(O.ORDERSELLINGPRICE- O.ORDERCOSTPRICE) AS ORDER_PROFITS
from 
{{ ref('stg_orders') }} AS O
LEFT JOIN 
{{ ref('stg_products')}} AS P 
ON O.PRODUCTID = P.PRODUCTID
LEFT JOIN 
{{ ref('stg_customers')}} AS C
ON O.CUSTOMERID = C.CUSTOMERID